# Generated by Django 6.0.3 on 2026-03-30 22:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flan",
            name="image_url",
        ),
        migrations.AddField(
            model_name="flan",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="flanes/"),
        ),
        migrations.AlterField(
            model_name="flan",
            name="flan_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
